"""
Django settings for auth_project project.
<<<<<<< HEAD
"""

from pathlib import Path
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-#rkutn+8p#g%511=t2b&!8^ajg4&^739x%ad@+8j4srn+w0^67"
=======

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-#rkutn+8p#g%511=t2b&!8^ajg4&^739x%ad@+8j4srn+w0^67'
>>>>>>> 9bebd6bc368c76f87785914b4ec6bf3487a1a978

DEBUG = True

ALLOWED_HOSTS = ["*"]

<<<<<<< HEAD
=======

>>>>>>> 9bebd6bc368c76f87785914b4ec6bf3487a1a978
# ---------------------------------------------------------
# APPLICATIONS
# ---------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

<<<<<<< HEAD
    'django_prometheus',   # ✅ ONLY ONCE

    'accounts',
=======
    # Your auth microservice app
    'accounts',

    # Third-party apps
    # 'corsheaders',
>>>>>>> 9bebd6bc368c76f87785914b4ec6bf3487a1a978
    'rest_framework',
    'rest_framework_simplejwt',
    'auth_frontend',
]


# ---------------------------------------------------------
# MIDDLEWARE
# ---------------------------------------------------------

MIDDLEWARE = [
<<<<<<< HEAD
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
=======
    # 'corsheaders.middleware.CorsMiddleware',  # must be near top
>>>>>>> 9bebd6bc368c76f87785914b4ec6bf3487a1a978

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
<<<<<<< HEAD

    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

# ---------------------------------------------------------
# URL / WSGI
# ---------------------------------------------------------

ROOT_URLCONF = "auth_project.urls"

WSGI_APPLICATION = "auth_project.wsgi.application"

# ---------------------------------------------------------
# TEMPLATES
# ---------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
=======
]


ROOT_URLCONF = 'auth_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
>>>>>>> 9bebd6bc368c76f87785914b4ec6bf3487a1a978
            ],
        },
    },
]

<<<<<<< HEAD
# ---------------------------------------------------------
# DATABASE  (PROMETHEUS ENABLED ENGINE)
# ---------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django_prometheus.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

=======
WSGI_APPLICATION = 'auth_project.wsgi.application'


# ---------------------------------------------------------
# DATABASE
# ---------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


>>>>>>> 9bebd6bc368c76f87785914b4ec6bf3487a1a978
# ---------------------------------------------------------
# PASSWORD VALIDATION
# ---------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
<<<<<<< HEAD
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

=======
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


>>>>>>> 9bebd6bc368c76f87785914b4ec6bf3487a1a978
# ---------------------------------------------------------
# INTERNATIONALIZATION
# ---------------------------------------------------------

<<<<<<< HEAD
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

=======
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


>>>>>>> 9bebd6bc368c76f87785914b4ec6bf3487a1a978
# ---------------------------------------------------------
# STATIC FILES
# ---------------------------------------------------------

<<<<<<< HEAD
STATIC_URL = "static/"

# ---------------------------------------------------------
# DJANGO PROMETHEUS (REQUIRED)
# ---------------------------------------------------------

# INSTALLED_APPS += ["django_prometheus"]
=======
STATIC_URL = 'static/'

>>>>>>> 9bebd6bc368c76f87785914b4ec6bf3487a1a978

# ---------------------------------------------------------
# REST FRAMEWORK + JWT
# ---------------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

<<<<<<< HEAD
=======
# SimpleJWT basic settings (default exp times are fine)
from datetime import timedelta
>>>>>>> 9bebd6bc368c76f87785914b4ec6bf3487a1a978
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}
<<<<<<< HEAD
=======


# ---------------------------------------------------------
# CORS SETTINGS
# ---------------------------------------------------------

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
>>>>>>> 9bebd6bc368c76f87785914b4ec6bf3487a1a978
